name: mm_inventory_web
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  flutter_animate: ^4.5.0
  responsive_builder: ^0.7.0
  url_strategy: ^0.2.0
  syncfusion_flutter_datagrid: ^30.2.6
  syncfusion_flutter_core: ^30.2.6
  syncfusion_flutter_charts: ^30.2.6
  dio: ^4.0.6
  retrofit: ^3.3.1
  flutter_dotenv: ^5.1.0
  get_it: ^7.6.7
  injectable: ^2.4.2
  intl: ^0.20.2
  google_fonts: ^6.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0
  retrofit_generator: ^4.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/gif/

